sonar.projectKey=pos-utils-common-metrics
sonar.projectName=pos-utils-common-metrics
sonar.sourceEncoding=UTF-8
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=src/main/java/com/kroger/metrics/annotation/**,\
                 src/main/java/com/kroger/metrics/constants/**