sonar.projectKey=pos-utils-common-metrics
sonar.projectName=pos-utils-common-metrics
sonar.sourceEncoding=UTF-8
sonar.sources=pos-utils-common-logging-core/src/main,pos-utils-common-logging-feign-client/src/main,\
              pos-utils-common-logging-rest-server/src/main,pos-utils-common-logging-ctx-camel-integration/src/main,\
              pos-utils-common-logging-ctx-ehub-publisher/src/main,pos-utils-common-logging-amqp-publisher/src/main
sonar.tests=pos-utils-common-logging-core/src/test,pos-utils-common-logging-feign-client/src/test,\
            pos-utils-common-logging-rest-server/src/test,pos-utils-common-logging-ctx-camel-integration/src/test,\
            pos-utils-common-logging-ctx-ehub-publisher/src/test,pos-utils-common-logging-amqp-publisher/src/test
sonar.java.binaries=pos-utils-common-logging-core/target/classes,pos-utils-common-logging-feign-client/target/classes,\
                    pos-utils-common-logging-rest-server/target/classes,pos-utils-common-logging-ctx-camel-integration/target/classes,\
                    pos-utils-common-logging-ctx-ehub-publisher/target/classes,pos-utils-common-logging-amqp-publisher/target/classes
sonar.coverage.jacoco.xmlReportPaths=pos-utils-common-logging-core/target/site/jacoco/jacoco.xml,\
                                     pos-utils-common-logging-feign-client/target/site/jacoco/jacoco.xml,\
                                     pos-utils-common-logging-rest-server/target/site/jacoco/jacoco.xml,\
                                     pos-utils-common-logging-ctx-camel-integration/target/site/jacoco/jacoco.xml,\
                                     pos-utils-common-logging-ctx-ehub-publisher/target/site/jacoco/jacoco.xml,\
                                     pos-utils-common-logging-amqp-publisher/target/site/jacoco/jacoco.xml
sonar.exclusions=pos-utils-common-logging-core/src/main/java/com/kroger/ngpos/common/logging/core/support/Constants.java,\
                 pos-utils-common-logging-feign-client/src/main/java/com/kroger/ngpos/common/logging/feignclient/constants/Constants.java,\
                 pos-utils-common-logging-rest-server/src/main/java/com/kroger/ngpos/common/logging/restserver/configuration/constants/Constants.java
