management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: health, metrics
  endpoint:
    prometheus:
      enabled: false
    metrics:
      enabled: true
    health:
      enabled: true

kind: Application