management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: health
  endpoint:
    prometheus:
      enabled: false
    health:
      enabled: true

kind: Application